name: simSPI
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - coverage
  - flake8-black
  - flake8-docstrings
  - flake8-import-order
  - numba
  - numpy
  - pip
  - pyfftw
  - pytest
  - pytest-cov
  - pip:
    - black==20.8b0
    - geomstats
    - git+https://github.com/comSPI/ioSPI.git
    - pre-commit
    - raster_geometry